services:
  - type: web
    plan: free
    name: gozne-seal
    env: docker
    autoDeploy: false
    repo: https://github.com/sabari-qwerty/render.git
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: docuseal-db
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
databases:
  - name: docuseal-db
    plan: free
